services:
  murky_api:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./tmp/db_backups:/db_backups
    env_file:
      - .env
    depends_on:
      - murky_api_redis
  murky_api_redis:
    image: redis:latest
