#!/bin/sh
set -eu

rsync -a --mkpath deploy/docker/docker-compose.yml "$SSH_HOST:$SERVER_APP_DIR/api2/"

ssh "$SSH_HOST" bash -s <<EOF
export CI_REGISTRY_IMAGE="$CI_REGISTRY_IMAGE"
export DB_DIR="$DB_DIR"
export ALLOWED_ORIGINS="$ALLOWED_ORIGINS"
export DB_FILE_PATH="$DB_FILE_PATH"
export GUEST_DB_FILE_PATH="$GUEST_DB_FILE_PATH"
export ACCESS_TOKEN_SECRET="$ACCESS_TOKEN_SECRET"
export REFRESH_TOKEN_SECRET="$REFRESH_TOKEN_SECRET"
export DB_BACKUP_DIR="$DB_BACKUP_DIR"
export REDIS_ADDRESS="$REDIS_ADDRESS"
export TIMEZONE="$TIMEZONE"
export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
export AWS_REGION="$AWS_REGION"
export AWS_ENDPOINT_URL="$AWS_ENDPOINT_URL"
export S3_BUCKET="$S3_BUCKET"
export S3_DB_BACKUP_PATH="$S3_DB_BACKUP_PATH"
export GOOGLE_SERVICE_ACCOUNT_KEY_FILE_CONTENT="$(echo "$GOOGLE_SERVICE_ACCOUNT_KEY_FILE_CONTENT" | base64 -w 0)"
export GOOGLE_SERVICE_ACCOUNT_KEY_FILE_PATH="$GOOGLE_SERVICE_ACCOUNT_KEY_FILE_PATH"
export BREVO_API_KEY="$BREVO_API_KEY"

cd $SERVER_APP_DIR/api2
docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
docker compose up -d --pull always --remove-orphans
EOF
